Repository krook1024/SZFM_2020_1_KP, pull requests merged in 2020-09, with the labels that each got.

#49 Rendszerterv - Üzleti folyamatok
  docs/rendszerspec/03_üzleti_folyamatok_modellje.md
  docs/rendszerspec/3_üzleti_folyamatok_modellje.md
Labels: documentation

#51 Rendszerterv - Adatbázisterv
  docs/rendszerspec/09_adatbázisterv.md
Labels: documentation

#52 Rendszerterv - Követelmények
  docs/rendszerspec/04_követelmények.md
  docs/rendszerspec/09_adatbázisterv.md
  docs/rendszerspec/3_üzleti_folyamatok_modellje.md
Labels: documentation

#27 Fill up '04_jelenlegi_uzleti_folyamatok.md' with content #26
  docs/kovspec/04_jelenlegi_uzleti_folyamatok.md
Labels: documentation, fix

#53 Rendszerspec 05 architekturális terv
  docs/rendszerspec/05_architekturalis_terv.md
Labels: documentation

#60 rename '06_igenyelt_uzletifolyamatok_modellje.md'
  docs/funkspec/06_igenyelt_uzletifolyamatok_modellje.md
Labels: fix

#32 Created "01_rendszer_celjai_es_nem_celjai.md" Closes #10
  docs/funkspec/01_rendszer_celjai_es_nem_celjai.md
Labels: documentation

#69 Added title for "02_jelenlegi_helyzet_leirasa.md" Closes #68
  docs/funkspec/02_jelenlegi_helyzet_leirasa.md
Labels: fix

#70 Created the Header Component
  package-lock.json
  package.json
  src/components/Header.js
  src/context/todo-context.js
  src/styles/App.css
  src/styles/Header.css
Labels: enhancement

#63 Alkalmazas adder
  src/App.js
  src/components/TodoAdd.js
  src/styles/TodoAdd.css
Labels: enhancement

#74 Finished the styling of the Header Component
  src/components/Header.js
  src/styles/Header.css
  src/styles/icons/menu-icon.svg
Labels: enhancement

#75 Alkalmazas Enhancements
  src/components/Header.js
  src/context/todo-context.js
Labels: enhancement

#72 Created "02_projektterv.md" for rendszerspec Closes #39
  docs/rendszerspec/02_projektterv.md
Labels: documentation

#71 Created "01_rendszer_celja.md" for rendszerspec Closes #38
  docs/rendszerspec/01_rendszer_celja.md
Labels: documentation

#78 Created "List component" for the application Closes #58
  src/components/TodoList.js
  src/styles/TodoList.css
Labels: enhancement

#79 Created "06_fizikai_környezet" for Rendszerspec Closes #42
  docs/rendszerspec/06_fizikai_környezet.md
Labels: documentation
